### ISSUE TITLE
Real-time updating issues

### ISSUE THREAD

**Issue by sheriffwoody0922** [sheriffwoody0922/nextjs-chat-app#3]
Implementing real-time updates for a chat app can be challenging. You may need to use WebSockets, Server-Sent Events, or other technologies to ensure that messages are delivered in real-time to all participants.

**Comment by fsdevchivalry** [comment]
To use WebSockets or Server-Sent Events (SSE) in a Next.js application, you can follow these general steps:

✨ Install necessary dependencies: Depending on whether you want to use WebSockets or SSE, you might need different libraries. For WebSockets, you could use libraries like socket.io-client, and for SSE, you may not need any additional libraries.

✨ Set up WebSocket or SSE server: You'll need a WebSocket server (such as socket.io for WebSockets) or an SSE server to handle the connections and data transmission.

✨ Create pages or components: In your Next.js application, create pages or components where you want to use WebSockets or SSE.

✨ Implement client-side code: In your Next.js pages or components, implement the client-side code to establish connections with the WebSocket server or SSE server, send/receive data, and update the UI accordingly.

**Comment by sheriffwoody0922** [comment]
Thank you for your information.
However, I still have problem with Firewall or proxy issues. If the application is behind a firewall or proxy, it might interfere with SSE connections. What's the solution of this problem?

**Comment by fsdevchivalry** [comment]
Hi, here are some steps you can take to address these issues:

🎗 Check firewall settings
🎗 Configure proxy settings
🎗 Use HTTPS
🎗 Use WebSocket fallback

By following these steps and adjusting your server configuration or firewall settings as needed, you should be able to resolve firewall or proxy issues with SSE in your Next.js application. If you're still experiencing issues, consider seeking assistance from a network administrator or consulting with experts familiar with your specific network environment.
